name: murts-sandbox
recipe: lamp
config:
  php: '8.1'
  webroot: app
  database: mysql
services:
  appserver:
    type: php:8.1 # Specify the desired PHP version
    webroot: /app/web
  database:
    type: mysql:5.7
    portforward: 3306

proxy:
  appserver:
    - murts.lndo.site

